name: Build and Deploy Hugo Site

on:
  workflow_dispatch:  # This allows for manual deploys

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Hugo
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Step 3: Build the Hugo site
      - name: Build Hugo site
        run: hugo

      # Step 4: Commit and push changes using token
      - name: Deploy changes
        run: |
          git config user.name "${{ secrets.USER_NAME }}"  # using secret for username
          git config user.email "${{ secrets.USER_EMAIL }}" # using secret for email
          git add public
          git commit -m "Deploy site"
          git push https://x-access-token:${{ secrets.tokens }}@github.com/SilentSmeary/hugo.git main
